--- #YAML:1.0
name: Posy-Plugin-FlavourMenu
version: 0.41
author:
  - Kathryn Andersen
abstract: Posy plugin to make a menu of flavours.
license: perl
requires:
  Posy: 0.9
  Posy::Plugin::YamlConfig: 0.41
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::FlavourMenu:
    file: lib/Posy/Plugin/FlavourMenu.pm
    version: 0.41
generated_by: Module::Build version 0.2607
